### ISSUE TITLE
Check Out Page

### ISSUE THREAD

**Issue by alishanvr** [therightsol/myshopping#14]
Hi,

Please set the checkout page (http://localhost:port/myshopping/checkout)

Do proper form validation and re-populating form values.
If user is logged in then get billing information from DB and put those values in billing info field. User must has a checkbox to confirm that these values are correct. If logged In user want to add new billing information then h/she can do this by removing populated values on just one click.

And if user is not available then ask user to enter billing information.

Regards,

**Comment by ob0981** [comment]
50% complete

**Comment by ob0981** [comment]
done but must be reviewed.
