### ISSUE TITLE
Create Menu

### ISSUE THREAD

**Issue by alishanvr** [therightsol/myshopping#5]
Hi,

Create three files for menu in **application / views / includes**.
1) annonymous_menu.inc
2) admin_menu.inc
3) member_menu.inc

Do not change or **delete menu.inc.php** file. We need to keep this file at current stage but we do not need to attach this file now.

Delete all extra links from every menu files. 

Currently there are many extra sub items in **menu.inc.php** file; Like Home2, Home3 etc. Do not copy unused links to our new three files. 

**1) annonymous_menu.inc** must has below links.
a)    Home
b)    Products 
c)    Shop (Shop link and sub items should be same as **menu.inc.php**
d)    Cart
e)    CheckOut
f)    Compare Products
g)     Contact Us
h)    About Us
i)    Register 
j)     Login

**2) admin_menu.inc** must has below links
a)    Home
b)    Products 
c)    Shop (Shop link and sub items should be same as **menu.inc.php**
d)    Cart
e)    CheckOut
f)    Compare Products
g)     Contact Us
h)    About Us
i)     Logout
j)     Dashboard
k)    Member

**3) member_menu.inc** must has below links
a)    Home
b)    Products 
c)    Shop (Shop link and sub items should be same as **menu.inc.php**
d)    Cart
e)    CheckOut
f)    Compare Products
g)   Member
h)   Contact Us
i)    About Us
j)     Logout

**Comment by ob0981** [comment]
completed all the three menu's for member, admin and anonymous user
