### ISSUE TITLE
Change Menu file [Pre-requisite : Solve issue #5]

### ISSUE THREAD

**Issue by alishanvr** [therightsol/myshopping#6]
Hi,

after resolving #5 You need to attach files in a dynamic fashion. Our system can change Menu Items based on type of logged in user. You can achieve this goal by including menu files based on which type of user is currently logged in.

I did the same thing in ad29724 commit (Lec 30)

Regards,

**Comment by ob0981** [comment]
Menu and Top bar is now Dynamic according to user type
