### ISSUE TITLE
Set Dashboard - Part 1

### ISSUE THREAD

**Issue by alishanvr** [therightsol/myshopping#7]
Hi,

set dashboard controller, views and assets properly. for example: dashboard should be open if I open http://localhost:port/myshopping/dashboard link. 

You need to create below functions / pages.

**Function Name:**   index
**Function File:**       dashboard.php (controller)
**URL:**   http://localhost:port/myshopping/dashboard
**View File**   applications / views / dashboard / home

**Function Name:**   login
**Function File:**       dashboard.php (controller)
**URL:**   http://localhost:port/myshopping/dashboard/login
**View File**   applications / views / dashboard / login

**Function Name:**   logout
**Function File:**       dashboard.php (controller)
**URL:**   http://localhost:port/myshopping/dashboard/logout
**View File**   applications / views / dashboard / logout

**Function Name:**   settings
**Function File:**       dashboard.php (controller)
**URL:**   http://localhost:port/myshopping/dashboard/settings
**View File**   applications / views / dashboard / settings

**Function Name:**   add_product
**Function File:**       dashboard.php (controller)
**URL:**   http://localhost:port/myshopping/dashboard/add_product
**View File**   applications / views / dashboard / add_product

**Function Name:**   view_all_products
**Function File:**       dashboard.php (controller)
**URL:**   http://localhost:port/myshopping/dashboard/view_all_products
**View File**   applications / views / dashboard / view_all_products

Regards,

**Comment by assad47** [comment]
some pages are not in our project(currently) .. but i've created all required pages..!!

**Comment by ramishahmed60** [comment]
re-open

**Comment by ramishahmed60** [comment]
Done sir !
