### ISSUE TITLE
Member Page / Member Area for Users

### ISSUE THREAD

**Issue by alishanvr** [therightsol/myshopping#8]
Hi,

Create a member page (based on our current layout, theme color and style). You can check attached image as sample. I like this member area. So, design like this but with green like color as per our front end. Because this page is for our members, where they can update / view different settings.

You are require to create a member page with these options:
1) **Account** <-- User can change / update his name, picture, and other registered meta values (if any)
2)  Change Password <-- User can change / update his/her password.
3)   Shipping Address <-- From here user can change / update his address
4)  My Orders <-- From Here user can view all of his / her orders and check status of each order and can check detail about each order and product etc.
5)  Privacy <--- Leave it blank. (If we have time in future then we will do this else not - But please create tab for privacy)
6) Disable Account <-- from here user can disable his / her account.

You are require to do some google for Bootstrap vertical tabs OR left side bar.
Some resources are as below:
**Vertical Tabs:**
http://bootsnipp.com/snippets/RlrN4
http://bootsnipp.com/snippets/OjPV

**Left Side bar:**
http://bootsnipp.com/snippets/featured/sidebar-menu-group-tree
http://bootsnipp.com/tags/sidebar
http://bootsnipp.com/snippets/featured/side-menu-on-hover
https://startbootstrap.com/template-overviews/simple-sidebar/
http://getbootstrap.com/examples/offcanvas/#

![screen-shot-2015-07-02-at-00 55 07](https://cloud.githubusercontent.com/assets/5610722/19902524/efa4c8ce-a08c-11e6-8a60-3d0c6c8b669d.png)

**Comment by assad47** [comment]
what about the member page i made before??

**Comment by alishanvr** [comment]
if it is working perfectly then you can use that else set it accordingly.
I gave you some reference websites from where you can learn about it. 

Regards,

**Comment by alishanvr** [comment]
check your FB account. I just sent you working / tested file.

**Comment by alishanvr** [comment]
@assad47 

this is not ur issue now.

@ramishahmed60  complete this issue asap.

**Comment by ramishahmed60** [comment]
okay sir
